import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { font } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <EdgeStoreProvider>{children}</EdgeStoreProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
